language: csharp
solution: src/src.csproj
mono: none
dotnet: 2.1.300
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      osx_image: xcode9.1
  fast_finish: true
script:
  - dotnet build -c "Release"
  - dotnet test  -c "Release"  
