name: CI

on: [push]

jobs:
  build:
    name: Build with ${{ matrix.dotnet }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04,macOS-10.14,windows-2016]
        dotnet: ['2.1.802','2.2.402','3.0.100']
        include:
          - os: ubuntu-18.04
            dotnet: '2.1.802'
            dotnet_name: netcoreapp2.1
          - os: ubuntu-18.04
            dotnet: '2.2.402'
            dotnet_name: netcoreapp2.2
          - os: ubuntu-18.04
            dotnet: '3.0.100'
            dotnet_name: netcoreapp3.0
          - os: macOS-10.14
            dotnet: '2.1.802'
            dotnet_name: netcoreapp2.1
          - os: macOS-10.14
            dotnet: '2.2.402'
            dotnet_name: netcoreapp2.2
          - os: macOS-10.14
            dotnet: '3.0.100'
            dotnet_name: netcoreapp3.0
          - os: windows-2016
            dotnet: '2.1.802'
            dotnet_name: netcoreapp2.1
          - os: windows-2016
            dotnet: '2.2.402'
            dotnet_name: netcoreapp2.2
          - os: windows-2016
            dotnet: '3.0.100'
            dotnet_name: netcoreapp3.0

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build with dotnet
      run: dotnet build -c "Release" "./src/src.csproj"
    - name: Test with dotnet
      run: dotnet test -c "Release" "./tests/tests.csproj" -f ${{ matrix.dotnet_name }} --no-build
